container:
  image: python:latest

test_task:

  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

  test_script: |
    set -x
    ls -l
    brew install csound
    python3 -m pip install .
    risset list
    risset install klib else

    csound -o test/lfnoise-macos-arm64-git.flac --format=flac test/lfnoise.csd

    ls test/*.flac

    csound -z1 2>&1 | grep dict_

