container:
  image: python:latest

test_task:

  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

  test_script: |
    set -x
    ls -l
    brew install csound
    python3 -m pip install .
    risset list
    risset install klib
    csound -z1 2>&1 | grep dict_

    csound -o test/lfnoise-macos-${{ matrix.arch }}-git.flac --format=flac test/lfnoise.csd
