on: [push]

jobs:
  testlinux:
    name: Test risset on linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install csound
        run: |
          sudo apt install csound csound libcsnd-dev
          csound --version
          mkdir -p artifacts

      - name: macos - test install from git
        run: |
          pip install .
          risset update
          risset list
          risset install klib else
          echo "-------------------------------"
          echo "Checking that the plugin is installed and recognized by csound"
          csound -z1 2>&1 | grep dict_
          csound -o test/lfnoise-linux-git.flac --format=flac test/lfnoise.csd
          cp test/*.flac artifacts

          risset remove klib else
          pip uninstall --yes risset

      - name: test install from pip
        run: |
          pip install risset -U
          risset update
          risset list
          risset install else
          echo "-------------------------------"
          echo "Checking that the plugin is installed and recognized by csound"
          csound -z1 2>&1 | grep atstop
          csound -o test/lfnoise-linux-pip.flac --format=flac test/lfnoise.csd
          cp test/*.flac artifacts

          risset remove else
          pip uninstall --yes risset


  testwin:
    name: Test risset on windows
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ "3.9" ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: windows - python ${{ matrix.python-version }} install csound
        run: |
          curl -L -o csound-binaries.zip https://github.com/csound/csound/releases/download/6.18.1/Csound-6.18.1-windows-x64-binaries.zip
          Expand-Archive csound-binaries.zip -DestinationPath "C:\Program Files\csound-binaries"
          ls -r "C:\Program Files\csound-binaries"

          [Environment]::SetEnvironmentVariable("PATH", $Env:PATH + ";C:\Program Files\csound-binaries\build\Release", [EnvironmentVariableTarget]::Machine)
          $Env:Path = $Env:Path + ";C:\Program Files\csound-binaries\build\Release"
          Write-Output $Env:PATH
          csound.exe --version

      - name: windows - test install from git
        run: |
          $Env:Path = $Env:Path + ";C:\Program Files\csound-binaries\build\Release"

          pip install .
          risset update
          risset list
          risset install klib
          echo "-------------------------------"
          echo "Checking that the plugin is installed and recognized by csound"
          csound -z1
          risset remove klib
          pip uninstall --yes risset

  testmacos:
    name: Test risset on macos
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.9"]
        arch: ["x86_64", "arm64"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: macos - install csound
        run: |
          curl -L -o csound6.18.dmg https://github.com/csound/csound/releases/download/6.18.1/Csound-MacOS-universal-6.18.1.dmg
          brew install p7zip
          7z x csound6.18.dmg
          cd Csound-universal-6.18.1
          sudo installer -pkg csound-MacOS-universal-6.18.1.pkg -target /
          csound --version
          cd ..

      - name: macos ${{ matrix.arch }} - test install from git
        run: |
          pip install .
          risset update
          risset list
          risset install klib else
          echo "-------------------------------"
          echo "Checking that the plugin is installed and recognized by csound"
          csound -z1 2>&1 | grep dict_
          csound -o test/lfnoise-macos-${{ matrix.arch }}-git.flac --format=flac test/lfnoise.csd

          mkdir -p artifacts
          cp test/*.flac artifacts

          brew install jq
          file $(risset info | jq -r .pluginspath)/*.so

          risset remove klib else
          pip uninstall --yes risset


      - name: macos ${{ matrix.arch }} - test install from pip
        run: |
          pip install risset -U
          risset update
          risset list
          risset install else
          echo "-------------------------------"
          echo "Checking that the plugin is installed and recognized by csound"
          csound -z1 2>&1 | grep atstop
          csound -o test/lfnoise-macos-${{ matrix.arch }}-pip.flac --format=flac test/lfnoise.csd

          mkdir -p artifacts
          cp test/*.flac artifacts

          risset remove else
          pip uninstall --yes risset
